CREATE TABLE "EOMORAOWNER"."DIMON_CALENDARS" 
   ("CALENDAR_NAME" VARCHAR2(100 BYTE), 
	"CALENDAR_SASCODE" VARCHAR2(1024 BYTE), 
	"UPDATE_USER" VARCHAR2(32 BYTE), 
	"UPDATE_DTS" TIMESTAMP, 
	 CONSTRAINT "PK_DIMON_CALENDARS" PRIMARY KEY ("CALENDAR_NAME")
	 );
	 
CREATE TABLE "EOMORAOWNER"."DIMON_FLOW_JOB" 
   (	"FLOW_JOB_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"FLOW_JOB_NAME" VARCHAR2(255 BYTE), 
	"FLOW_ID" VARCHAR2(20 BYTE), 
	"JOB_ID" VARCHAR2(20 BYTE), 
	"JOB_SEQ_NR" SMALLINT, 
	"VALID_FROM_DTS" TIMESTAMP, 
	"VALID_UNTIL_DTS" TIMESTAMP, 
	"CURRENT_IND" VARCHAR2(1 BYTE), 
	"UPDATE_USER" VARCHAR2(32 BYTE), 
	"UPDATE_DTS" TIMESTAMP, 
	 CONSTRAINT "PK_DIMON_FLOW_JOB" PRIMARY KEY ("FLOW_JOB_ID", "VALID_FROM_DTS")	 
	 );

CREATE TABLE "EOMORAOWNER"."DIMON_FLOW_SCHEDULES" 
   (	"FLOW_ID" VARCHAR2(20 BYTE), 
	"TRIGGERING_EVENT_TRANSFER_ROLE" VARCHAR2(10 BYTE), 
	"TRIGGERING_EVENT_ROLE" VARCHAR2(20 BYTE), 
	"TRIGGERING_EVENT_CONDITION" VARCHAR2(100 BYTE), 
	"TIMEZONE" VARCHAR2(32 BYTE), 
	"VALID_FROM_DTS" TIMESTAMP, 
	"VALID_UNTIL_DTS" TIMESTAMP, 
	"CURRENT_IND" VARCHAR2(1 BYTE), 
	"UPDATE_USER" VARCHAR2(32 BYTE), 
	"UPDATE_DTS" TIMESTAMP,
	 CONSTRAINT "PK_DIMON_FLOW_SCHEDULES" PRIMARY KEY ("FLOW_ID", "TRIGGERING_EVENT_CONDITION", "VALID_FROM_DTS")	 
   );
   
CREATE TABLE "EOMORAOWNER"."DIMON_FLOWS" 
   (	"FLOW_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FLOW_NAME" VARCHAR2(100 BYTE), 
	"FLOW_DESC" VARCHAR2(200 BYTE), 
	"VALID_FROM_DTS" TIMESTAMP, 
	"VALID_UNTIL_DTS" TIMESTAMP, 
	"CURRENT_IND" VARCHAR2(1 BYTE), 
	"UPDATE_USER" VARCHAR2(32 BYTE), 
	"UPDATE_DTS" TIMESTAMP, 
	 CONSTRAINT "PK_DIMON_FLOWS" PRIMARY KEY ("FLOW_ID", "VALID_FROM_DTS")
	 );

	 CREATE TABLE "EOMORAOWNER"."DIMON_HIDE_FLOWS" 
   (	"FLOW_ID" VARCHAR2(20 BYTE), 
	"HIDE_IND" VARCHAR2(1 BYTE), 
	"VALID_FROM_DTS" TIMESTAMP, 
	"VALID_UNTIL_DTS" TIMESTAMP, 
	"CURRENT_IND" VARCHAR2(1 BYTE), 
	"UPDATE_USER" VARCHAR2(32 BYTE), 
	"UPDATE_DTS" TIMESTAMP, 
	 CONSTRAINT "PK_DIMON_HIDE_FLOWS" PRIMARY KEY ("FLOW_ID", "VALID_FROM_DTS")
	 );
	 
CREATE TABLE "EOMORAOWNER"."DIMON_JOB_RUNS" 
   (	"JOB_RUN_ID" INTEGER NOT NULL ENABLE, 
	"FLOW_RUN_ID" INTEGER, 
	"FLOW_RUN_SEQ_NR" SMALLINT, 
	"FLOW_JOB_ID" VARCHAR2(255 BYTE), 
	"JOB_START_DTS" TIMESTAMP (6), 
	"JOB_END_DTS" TIMESTAMP (6), 
	"JOB_LOG_FILE" VARCHAR2(1024 BYTE), 
	"JOB_LST_FILE" VARCHAR2(1024 BYTE), 
	"JOB_STATUS_ID" SMALLINT, 
	"JOB_RC" SMALLINT, 
	"UPDATE_USER" VARCHAR2(32 BYTE), 
	"UPDATE_DTS" TIMESTAMP, 
	 CONSTRAINT "PK_DIMON_JOB_RUNS" PRIMARY KEY ("JOB_RUN_ID")
	 );
CREATE INDEX "EOMORAOWNER"."DIMON_JOB_RUNS_IDX1" ON "EOMORAOWNER"."DIMON_JOB_RUNS" ("FLOW_RUN_ID");

CREATE TABLE "EOMORAOWNER"."DIMON_JOB_STATUS" 
   (	"JOB_STATUS_ID" SMALLINT NOT NULL ENABLE, 
	"JOB_STATUS_CODE" VARCHAR2(12 BYTE), 
	"JOB_STATUS_DESC" VARCHAR2(32 BYTE), 
	"JOB_STATUS_SEQUENCE_NR" NUMBER(*,0), 
	 CONSTRAINT "PK_DIMON_JOB_STATUS" PRIMARY KEY ("JOB_STATUS_ID")
	 );

CREATE TABLE "EOMORAOWNER"."DIMON_JOBS" 
   (	"JOB_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"JOB_NAME" VARCHAR2(100 BYTE), 
	"VALID_FROM_DTS" TIMESTAMP, 
	"VALID_UNTIL_DTS" TIMESTAMP, 
	"CURRENT_IND" VARCHAR2(1 BYTE), 
	"UPDATE_USER" VARCHAR2(32 BYTE), 
	"UPDATE_DTS" TIMESTAMP, 
	 CONSTRAINT "PK_DIMON_JOBS" PRIMARY KEY ("JOB_ID", "VALID_FROM_DTS")
	 );

CREATE TABLE "EOMORAOWNER"."DIMON_RUN_STATS" 
   (	"FLOW_JOB_ID" VARCHAR2(255 BYTE), 
	"STATS_DTS_FROM" TIMESTAMP, 
	"STATS_DTS_UNTIL" TIMESTAMP, 
	"STATS_DATE" TIMESTAMP, 
	"ELAPSED_TIME" REAL, 
	"ELAPSED_TIME_Q1" REAL, 
	"ELAPSED_TIME_MEDIAN" REAL, 
	"ELAPSED_TIME_Q3" REAL, 
	"ELAPSED_TIME_IQR" REAL, 
	"ELAPSED_TIME_OUTLIER_IND" SMALLINT, 
	"ELAPSED_TIME_OUTLIER" REAL, 
	"ELAPSED_TIME_NON_OUTLIER" REAL, 
	"ELAPSED_TIME_MOVAVG" REAL, 
	"ELAPSED_TIME_MOVSTD" REAL, 
	"ELAPSED_TIME_LCL95" REAL, 
	"ELAPSED_TIME_UCL95" REAL, 
	"INTERPOLATED_IND" VARCHAR2(1 BYTE), 
	"UPDATE_USER" VARCHAR2(32 BYTE), 
	"UPDATE_DTS" TIMESTAMP, 
	 CONSTRAINT "PK_DIMON_RUN_STATS" PRIMARY KEY ("FLOW_JOB_ID", "STATS_DTS_FROM")
	 );
	 
CREATE TABLE "EOMORAOWNER"."DIMON_TIMEZONES" 
   (	"TIMEZONE" VARCHAR2(32 BYTE), 
	"CONDITION_SASCODE" VARCHAR2(1024 BYTE), 
	"CONDITION_DESC" VARCHAR2(100 BYTE), 
	"TIMEDIFF" SMALLINT, 
	"UPDATE_USER" VARCHAR2(32 BYTE), 
	"UPDATE_DTS" TIMESTAMP,
    CONSTRAINT "PK_DIMON_TIMEZONES" PRIMARY KEY ("TIMEZONE", "TIMEDIFF")
	);


INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Daily@Sys','1', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('First_day_of_year@Sys', 'd = intnx(''year'',d,0,''beginning'')', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Last_day_of_year@Sys', 'd = intnx(''year'',d,0,''end'')', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('First_day_of_month@Sys', 'd = intnx(''month'',d,0,''beginning'')', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Last_day_of_month@Sys', 'd = intnx(''month'',d,0,''end'')', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Weekdays@Sys', 'weekday(d) in (2,3,4,5,6)', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Weekends@Sys', 'weekday(d) in (1,7)', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Sundays@Sys', 'weekday(d) = 1', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Mondays@Sys', 'weekday(d) = 2', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Tuesdays@Sys', 'weekday(d) = 3', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Wednesdays@Sys', 'weekday(d) = 4', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Thursdays@Sys', 'weekday(d) = 5', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Fridays@Sys', 'weekday(d) = 6', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Saturdays@Sys', 'weekday(d) = 7', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('First_weekday_of_month@Sys', 'd = (intnx(''month'',d,0,''beginning'') + 2*(weekday(intnx(''month'',d,0,''beginning'')) = 7) + (weekday(intnx(''month'',d,0,''beginning'')) = 1) )', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Last_weekday_of_month@Sys', 'd = (intnx(''month'',d,0,''end'') - 2*(weekday(intnx(''month'',d,0,''end'')) = 1) - 1*(weekday(intnx(''month'',d,0,''end'')) = 7) )', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('First_sunday_of_month@Sys', 'weekday(d) = 1 and day(d) <= 7', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('First_monday_of_month@Sys', 'weekday(d) = 2 and day(d) <= 7', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('First_tuesday_of_month@Sys', 'weekday(d) = 3 and day(d) <= 7', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('First_wednesday_of_month@Sys', 'weekday(d) = 4 and day(d) <= 7', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('First_thursday_of_month@Sys', 'weekday(d) = 5 and day(d) <= 7', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('First_friday_of_month@Sys', 'weekday(d) = 6 and day(d) <= 7', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('First_saturday_of_month@Sys', 'weekday(d) = 7 and day(d) <= 7', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Last_sunday_of_month@Sys', 'weekday(d) = 1 and d >= (intnx(''month'',d,0,''end'') - 6)', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Last_monday_of_month@Sys', 'weekday(d) = 2 and d >= (intnx(''month'',d,0,''end'') - 6)', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Last_tuesday_of_month@Sys', 'weekday(d) = 3 and d >= (intnx(''month'',d,0,''end'') - 6)', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Last_wednesday_of_month@Sys', 'weekday(d) = 4 and d >= (intnx(''month'',d,0,''end'') - 6)', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Last_thursday_of_month@Sys', 'weekday(d) = 5 and d >= (intnx(''month'',d,0,''end'') - 6)', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Last_friday_of_month@Sys', 'weekday(d) = 6 and d >= (intnx(''month'',d,0,''end'') - 6)', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Last_saturday_of_month@Sys', 'weekday(d) = 7 and d >= (intnx(''month'',d,0,''end'') - 6)', USER, CURRENT_TIMESTAMP);
INSERT INTO DIMON_CALENDARS (CALENDAR_NAME,CALENDAR_SASCODE,UPDATE_USER,UPDATE_DTS) VALUES ('Businessdays@Sys', 'weekday(d) >= 2 and weekday(d) <= 6', USER, CURRENT_TIMESTAMP);

INSERT INTO DIMON_JOB_STATUS (JOB_STATUS_ID,JOB_STATUS_CODE,JOB_STATUS_DESC,JOB_STATUS_SEQUENCE_NR) VALUES (0,'NOT STARTED','Not Started',1);
INSERT INTO DIMON_JOB_STATUS (JOB_STATUS_ID,JOB_STATUS_CODE,JOB_STATUS_DESC,JOB_STATUS_SEQUENCE_NR) VALUES (1,'RUNNING','Running',2);
INSERT INTO DIMON_JOB_STATUS (JOB_STATUS_ID,JOB_STATUS_CODE,JOB_STATUS_DESC,JOB_STATUS_SEQUENCE_NR) VALUES (2,'COMPLETED','Completed',3);

INSERT INTO DIMON_TIMEZONES (TIMEZONE,CONDITION_SASCODE,CONDITION_DESC,TIMEDIFF,UPDATE_USER,UPDATE_DTS) VALUES ('UTC','dts > dhms(intnx(''week.1'',intnx(''month'',mdy(3,1,year(datepart(dts))),0,''E''),0,''B''),2,0,0) and dts < dhms(intnx(''week.1'',intnx(''month'',mdy(10,1,year(datepart(dts))),0,''E''),0,''B''),2,0,0)','UTC Daylight Saving Time',7200,USER,CURRENT_TIMESTAMP);
INSERT INTO DIMON_TIMEZONES (TIMEZONE,CONDITION_SASCODE,CONDITION_DESC,TIMEDIFF,UPDATE_USER,UPDATE_DTS) VALUES ('UTC','dts <= dhms(intnx(''week.1'',intnx(''month'',mdy(3,1,year(datepart(dts))),0,''E''),0,''B''),2,0,0) or dts >= dhms(intnx(''week.1'',intnx(''month'',mdy(10,1,year(datepart(dts))),0,''E''),0,''B''),2,0,0)','UTC No Daylight Saving Time',3600,USER,CURRENT_TIMESTAMP);

COMMIT;
